name: beginapp01
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.3
  font_awesome_flutter: ^10.8.0
  table_calendar: ^3.1.2
  flutter_localizations:
    sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/splash_animation.json
    - assets/images/login.png
    - assets/images/appoinment.png
    - assets/images/dashboard.png
    - assets/images/diagnosis.png
    - assets/images/doctor.png
    - assets/images/money-bag.png
    - assets/images/pharmacy.png
    - assets/images/prescription.png
    - assets/images/report.png
    - assets/images/patient.png
    - assets/images/reset.png
  fonts:
    - family: ComicsSan
      fonts:
        - asset: assets/fonts/ComicSan.ttf
    - family: UTM
      fonts:
        - asset: assets/fonts/UTMImpact.ttf


